### ISSUE TITLE
微信登录有bug

### ISSUE THREAD

**Issue by blingblingmin007** [cosin2077/chaty#2]
错误如下：
https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FoYlBGtR2Ag%3D%3D

uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/usr/local/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)
    at /usr/local/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/usr/local/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /usr/local/lib/node_modules/ichaty/lib/src/services/wechat/node_modules/wechat4u/lib/core.js:227:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by wirender** [comment]
能否提供下node 版本和操作系统版本

**Comment by jianxiutou5** [comment]
请问微信是怎么登陆的？我扫完码，没发现有什么变化，不知道在哪展开对话呢

**Comment by yanwuhen** [comment]
> 

我也是相同的报错，node版本v18.15.0，OS是Debian 11。

**Comment by cosin2077** [comment]
请检查自己的微信号是否实名过了

**Comment by cosin2077** [comment]
> 

正常的流程扫完码，微信应该提示 确认登录，登录成功手机微信上边会提示 桌面微信已经登录如下图
<img width="387" alt="image" src="https://user-images.githubusercontent.com/20504493/224882896-76b1d967-b172-42e1-a4ef-f6abea7177cb.png">

**Comment by jianxiutou5** [comment]
：）
为了保障你的帐号安全，暂不支持使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。

**Comment by cosin2077** [comment]
> ：） 为了保障你的帐号安全，暂不支持使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。

UOS能实现这个，确保实名完成后，可以再次扫码登录尝试

**Comment by jianxiutou5** [comment]
> > ：） 为了保障你的帐号安全，暂不支持使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。
> 
> UOS能实现这个，确保实名完成后，可以再次扫码登录尝试

多谢
