### ISSUE TITLE
微信生成的码扫不出来

### ISSUE THREAD

**Issue by mengxuntianya** [cosin2077/chaty#3]
win10 ，windows 2012, Windows (x64) nodejs 18.15.0 LTS，生成的二维码都扫不出来，麻烦看一下。
![微信截图_20230311214618](https://user-images.githubusercontent.com/47874296/224488240-3a6df4a5-0f31-4f05-9edf-e5e6e459fcc0.png)
![微信截图_20230311212909](https://user-images.githubusercontent.com/47874296/224488246-0fc93bea-15e7-4f9b-9054-8dc7af0f4b5e.png)

**Comment by cosin2077** [comment]
暂时的解决方案可以点击二维码下边的链接扫码登录，
该问题会继续跟进

**Comment by mengxuntianya** [comment]
> 暂时的解决方案可以点击二维码下边的链接扫码登录， 该问题会继续跟进

感谢回复，复制链接确实正常显示了，但用微信扫码后没有任何反应，请教一下要什么处理？

**Comment by mengxuntianya** [comment]
看到命令行有报错了。
![微信截图_20230312090631](https://user-images.githubusercontent.com/47874296/224518704-30f78ebb-071a-4ece-9138-fd52bd4c1d0d.png)

**Comment by mengxuntianya** [comment]
复制生成地址在浏览器，有个报错一闪而过，page not found, 然后跳出了正常的二维码，但扫了没有任何反应。
![微信截图_20230312093744](https://user-images.githubusercontent.com/47874296/224519510-5590fdf8-8f9b-4c63-aff4-865d5f4db214.png)

**Comment by cosin2077** [comment]
> 看到命令行有报错了。 ![微信截图_20230312090631](https://user-images.githubusercontent.com/47874296/224518704-30f78ebb-071a-4ece-9138-fd52bd4c1d0d.png)

https://github.com/cosin2077/chaty/blob/main/README.zh-CN.md#troubleshooting
这应该是微信需要实名的报错
