### ISSUE TITLE
ichaty login <your-openAI-key> 提示找不到命令 ichaty

### ISSUE THREAD

**Issue by mylysddp** [cosin2077/chaty#5]
按照前面的安装步骤npm 安装chaty,安装之后提示找不到ichaty 和 chaty
<img width="704" alt="image" src="https://user-images.githubusercontent.com/22786323/224520489-5b16316f-a71b-4720-9ee3-359d53dd0047.png">

**Comment by serendipityoflife** [comment]
方便给下node版本和操作系统版本嘛

**Comment by cosin2077** [comment]
能否看下node版本和操作系统版本
mac安装全局包需要加sudo
