### ISSUE TITLE
不是很理解你设置这个header的意思

### ISSUE THREAD

**Issue by Minweiwangaaaa** [cosin2077/chaty#6]
headers.origin = 'https://app.uniswap.org'

为啥要设置uniswap。。。

**Comment by serendipityoflife** [comment]
因为临时代理需要一个origin，而uniswap是这个临时代理常见的origin。
临时代理仅做demo和个人使用。
最好是自建代理，稳定且可自定义

**Comment by cosin2077** [comment]
因为临时代理需要一个origin，而uniswap是这个临时代理常见的origin。
临时代理仅做demo和个人使用。
最好是自建代理，稳定且可自定义
