### ISSUE TITLE
一直处在 `starting to check chaty version...` 状态

### ISSUE THREAD

**Issue by jacob-rodgers-max** [cosin2077/chaty#7]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/121411450/224528740-1880b920-1a21-4486-980c-9367cebdd3f3.png">
是我网络问题吗，全局代理也试了

**Comment by cosin2077** [comment]
请问下你的node版本和操作系统版本是什么

**Comment by Jason-story** [comment]
我也是一样的情况
node 18.14.2
macos 13.2.1

**Comment by cosin2077** [comment]
> 我也是一样的情况 node 18.14.2 macos 13.2.1  

能否运行下 chaty login xxxx -d , 打开调试模式，看下log

**Comment by cosin2077** [comment]
> 我也是一样的情况 node 18.14.2 macos 13.2.1

最新版已经解决此问题
